# SPDX-FileCopyrightText: Copyright © 2025 The Dymes project authors
#
# SPDX-License-Identifier: Apache-2.0
name: Build and publish OCI images

on:
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    #tags: [ 'v*.*.*' ]
#  pull_request:
#    branches: ["main"]

jobs:
  build-with-chart:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-latest

    env:
      ORG_NAME: see-further
      PROJECT_NAME: dymes
      PROJECT_FORMER_NAME: dimes
      ENV: dev

    steps:
      - name: Print GitHub context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Ref: $GITHUB_REF"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Release build
        id: release-build-step
        # if: github.event_name != 'pull_request'
        run: make release

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::157305260194:role/GitHubECRPushPolicy
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.62.0
        id: bump_tag
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          DRY_RUN: ${{ github.ref != 'refs/heads/develop' }}
          WITH_V: true
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: develop
          PRERELEASE: ${{ github.ref != 'refs/heads/develop' }}

      - name: Extract number from new tag
        id: version_number_extract
        env:
          NEW_TAG: ${{ steps.bump_tag.outputs.new_tag }}
        run: |
          echo "version=$( echo $NEW_TAG | sed 's/^.//')" >> "$GITHUB_OUTPUT"

      - name: Print latest version number string
        env:
          NEW_TAG: ${{ steps.bump_tag.outputs.new_tag }}
        run: |
          echo ${{ steps.bump_tag.outputs.new_tag }}
          echo ${{ steps.bump_tag.outputs.tag }}
          echo ${{ steps.bump_tag.outputs.part }}
          echo ${{ steps.version_number_extract.outputs.version }}

      - name: Helm Unittest
        uses: d3adb5/helm-unittest-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        with:
          charts: "charts/${{ env.PROJECT_FORMER_NAME }}/"
          helm-version: v3.19.0
          
      - name: Prep helm chart with version
        env:
          APP_VERSION: ${{ steps.version_number_extract.outputs.version }}
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DOCKER_REPOSITORY: ${{ env.ORG_NAME }}/${{ env.PROJECT_NAME }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "charts/${{ env.PROJECT_FORMER_NAME }}/values.yaml"
          propertyPath: 'image.repository'
          value: "${{ steps.login-ecr.outputs.registry }}/${{ env.ORG_NAME}}"

      - name: Lint Helm charts
        run: |
          helm lint --strict charts/${{ env.PROJECT_FORMER_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DOCKER_REPOSITORY: ${{ env.ORG_NAME }}/${{ env.PROJECT_NAME }}
          IMAGE_TAG: ${{ steps.version_number_extract.outputs.version }}
          ENV: ${{ env.ENV }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG --push .
          echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"

      - name: Build helm chart
        env:
          CHART_VERSION: ${{ steps.version_number_extract.outputs.version }}
        run:  |
          helm dependency build charts/${PROJECT_FORMER_NAME}
          helm package --version ${CHART_VERSION} --app-version ${CHART_VERSION} charts/${PROJECT_FORMER_NAME}
  
      - name: Push helm chart
        if: github.ref == 'refs/heads/develop'
        env:
          HELM_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          CHART_VERSION: ${{ steps.version_number_extract.outputs.version }}
        run: |
          echo "Target is oci://${{ steps.login-ecr.outputs.registry }}"
          helm push ${PROJECT_NAME}-${CHART_VERSION}.tgz oci://${HELM_REGISTRY}/${ORG_NAME}/chart --debug
